fn main() {
    // define the rule
    let logic = bme::Logic::default();

    println!(
        "{}",
        serde_json::to_string_pretty(&logic.get_json()).unwrap()
    );
    println!("");

    // parse the code from json to the objects
    let json = r#"[{"blockId":1,"blockTypeId":1,"position":{"x":271,"y":87},"nodes":[{"id":0,"nodeType":"output","connectionType":"Execution","value":null,"connectedBlockId":2,"connectedBlockTypeId":2,"connectedNodeId":0}]},{"blockId":2,"blockTypeId":2,"position":{"x":457,"y":92},"nodes":[{"id":0,"nodeType":"input","connectionType":"Execution","value":null,"connectedBlockId":1,"connectedBlockTypeId":1,"connectedNodeId":0},{"id":1,"nodeType":"output","connectionType":"Execution","value":null,"connectedBlockId":3,"connectedBlockTypeId":2,"connectedNodeId":0},{"id":2,"nodeType":"input","connectionType":"String","value":"Hello","connectedBlockId":null,"connectedBlockTypeId":null,"connectedNodeId":null}]},{"blockId":4,"blockTypeId":3,"position":{"x":451,"y":221},"nodes":[{"id":2,"nodeType":"input","connectionType":"String","value":"World","connectedBlockId":null,"connectedBlockTypeId":null,"connectedNodeId":null},{"id":3,"nodeType":"output","connectionType":"String","value":null,"connectedBlockId":3,"connectedBlockTypeId":2,"connectedNodeId":2}]},{"blockId":3,"blockTypeId":2,"position":{"x":765,"y":121},"nodes":[{"id":0,"nodeType":"input","connectionType":"Execution","value":null,"connectedBlockId":2,"connectedBlockTypeId":2,"connectedNodeId":1},{"id":1,"nodeType":"output","connectionType":"Execution","value":null,"connectedBlockId":5,"connectedBlockTypeId":2,"connectedNodeId":0},{"id":2,"nodeType":"input","connectionType":"String","value":null,"connectedBlockId":4,"connectedBlockTypeId":3,"connectedNodeId":3}]},{"blockId":5,"blockTypeId":2,"position":{"x":1048,"y":155},"nodes":[{"id":0,"nodeType":"input","connectionType":"Execution","value":null,"connectedBlockId":3,"connectedBlockTypeId":2,"connectedNodeId":1},{"id":1,"nodeType":"output","connectionType":"Execution","value":null,"connectedBlockId":null,"connectedBlockTypeId":null,"connectedNodeId":null},{"id":2,"nodeType":"input","connectionType":"String","value":null,"connectedBlockId":6,"connectedBlockTypeId":3,"connectedNodeId":3}]},{"blockId":6,"blockTypeId":3,"position":{"x":790,"y":291},"nodes":[{"id":2,"nodeType":"input","connectionType":"String","value":null,"connectedBlockId":7,"connectedBlockTypeId":3,"connectedNodeId":3},{"id":3,"nodeType":"output","connectionType":"String","value":null,"connectedBlockId":5,"connectedBlockTypeId":2,"connectedNodeId":2}]},{"blockId":7,"blockTypeId":3,"position":{"x":498,"y":338},"nodes":[{"id":2,"nodeType":"input","connectionType":"String","value":"!!!","connectedBlockId":null,"connectedBlockTypeId":null,"connectedNodeId":null},{"id":3,"nodeType":"output","connectionType":"String","value":null,"connectedBlockId":6,"connectedBlockTypeId":3,"connectedNodeId":2}]}]"#;

    let mut exe = bme::Executer::new(json.to_string());
    exe.execute().unwrap();
}